### ISSUE TITLE
PMD Nano framerate

### ISSUE THREAD

**Issue by rocklinsuv** [taketwo/pmd_camboard_nano#7]
Hi Sergey,

I've started to use the nano again. This time I'm wondering if the framerate can be adjusted, since I didn't see any params in the launch file. Besides, if I convert the amplitude image in OpenCV format, and just extract several points instead of the whole image for processing, will it speed up the process? I've test it on my quadrotor, the performance is terrible if I process the whole image. Many thanks!

Cheers,
Lyn

**Comment by taketwo** [comment]
Hi, as mentioned in the README, the frame rate can be adjusted with `~update_rate` node parameter. As for the second question, I can imagine that the main bottleneck is in [these lines](https://github.com/taketwo/pmd_camboard_nano/blob/master/src/pmd_camboard_nano.cpp#L264-L289). If you don't need points projected in 3D, then don't subscribe to the point cloud topic, and the time won't be spent calculating their coordinates. If the performance is bad even when subscribed only to amplitude topic, then try to disable vertical flipping and/or removal of invalid pixels.

**Comment by rocklinsuv** [comment]
Hi Sergey,

I tried to use PCL functions with the Nano, which gives me quite good results. 
This time I have some other questions about camera calibration. As the driver loads the .dat file containing the camera intrinsic paramerters at the beginning, does it do the calibration onboard or using the CPU's computational power?
My second question will be, if I put a regular camera (VGA resolution) close to the Nano, baseline of which is only several cm, is there any potential way to find the Fundamental Matrix/Essential Matrix of the two cameras? Say, if I know the pixel coordinate of a point in the VGA camera, what if I want to calculate the corresponding pixel corrdinate in the Nano? I have a feeling that I need to modify the Essential Matrix equation but don't know how (maybe I need a scaling factor?)
Thanks again. I'm looking forward to your reply.


Cheers,
Lyn

**Comment by taketwo** [comment]
Hi, I'm not sure what you mean by  "do calibration" when it comes to the ROS camera driver. As you mentioned, the intrinsic parameters are loaded from a `.dat` file. These parameters are given to the PMD camera driver and also published to the ROS network. That is it. Apart from that, nothing is being done, no online (re-)calibration or whatever.

For the second question I suggest you to look into the relevant literature. What you want to achieve is extrinsic calibration between a depth and a color camera. For example, [this paper](http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6205765) seems relevant, also they provide open source toolbox.

**Comment by rocklinsuv** [comment]
Ummm, thank you for the quick reply.
That means I have to do the calibration to correct the barrel distortion myself, which takes a certain amout of time.
For the second question, I've done a lot of searches but end up with nothing.....including ROS Answer, StackOverflow......I truly appreciate your help!

Cheers,
Lyn

**Comment by taketwo** [comment]
You are welcome! Can we close this?

**Comment by rocklinsuv** [comment]
Sure. Please do, thanks again!


Cheers,
Lyn

Sent from my HTC

----- Reply message -----

**Comment by rocklinsuv** [comment]
Hi Sergey,
Sorry to bother you again. I'm experiencing a weird issue getting the depth image from the Nano.Say I have a white marker painted on a dark background, which looks like this:    

Actually it is a plane, but the PMD is giving me bright/dark pixels. Does it mean that I can't use this image to do the plane fitting?I haven't checked the point cloud data yet, but I would like to hear your opinion first. Many thanks.

Cheers,Lyn

**Comment by taketwo** [comment]
Can't see the figure.

**Comment by rocklinsuv** [comment]
Hi,

Do you have a hotmail mailbox or something? I was replying the github email so maybe that's the problem. Once I reach home I can re-send it. Many thanks.

Cheers,

Sent from my HTC

----- Reply message -----

**Comment by rocklinsuv** [comment]
Hi Sergey,
I've send an email with the figure to your gmail mailbox. Thanks.

Cheers,

Lyn

**Comment by rocklinsuv** [comment]
Hi Sergey,

Have you received my email? Still haven't figured out why the PMD depth image looked like that.
I truly appreciate if you have give me some hints to explain the phenomenon.

Cheers,
Lyn
